### ISSUE TITLE
address list output order

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#105]
I've noticed that the addresses without labels are being output in a different order on each `address list` call. Maybe it would make sense to chose any rule that would fix their order somehow.

**Comment by d5000** [comment]
This is a bit more complicated than a few lines of code, and it's low-priority afaik. It's likely I'll address this issue in the future because I plan to streamline the address list command a bit.

**Comment by buhtignew** [comment]
Should we close this issue or it's useful for you to keep it open?

**Comment by d5000** [comment]
In these cases please keep the issue open.

**Comment by d5000** [comment]
To be able to close this issue I have reworked the address list command a bit. It was a total mess because I had added a lot of functions and in the end its structure was totally chaotic. Now it's much easier to maintain.

In addition, the address list output order is now also predictable:

- first the named addresses, in alphabetical order
- then the unnamed addresses, also in alphabetical order.

Commit is 00ed83e. If everything works this issue can be closed, was already pre-tested as I've fixed my client problems.

**Comment by buhtignew** [comment]
This works, the only thing I'd like to ask:
Is it possible that `address list` command has become slower?

**Comment by d5000** [comment]
In theory that would not surprise me because before the addresses were unsorted. But I just checked it on my device and it's the other way around: address list without any flags in the old version took 3:59 minutes, in the new version 3:48. (I have lots of addresses, thus it takes long).

I also fixed a problem with the advanced mode (`-a`) which now should be significantly faster, it took sometimes more than a hour before because it got stuck on tokens which were not initialized. Now it takes "only" around 7 minutes.

**Comment by buhtignew** [comment]
>...in the new version 3:48. (I have lots of addresses, thus it takes long).

It takes about 30 seconds on my side. You should have a enormous quantity of addresses then.

> I also fixed a problem with the advanced mode (-a) which now should be significantly faster, it took sometimes more than a hour before because it got stuck on tokens which were not initialized. Now it takes "only" around 7 minutes.

Here it requires about 58 seconds.

> ...I suggest to upgrade to the newest version.

Done

Closing this since everything seems to solved in this issue.
