### ISSUE TITLE
Double values in blocklocator.json file

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#117]
I've discovered that some blockheight is mentioned twice in my blocklocator.json file (
[blocklocator.json](https://github.com/user-attachments/files/15606975/blocklocator.json)
Specifically 156889 and 381560 is it expected?

**Comment by d5000** [comment]
This was fixed in the commits up to 7c31f67ddae0acf7b1bda1ef83936e79f17a3c0a. I had seen the part of the command which could have caused the duplicates, and changed that part so it doesn't happen again (blockheights which are already in the JSON files simply aren't stored).

The duplicates which are there now aren't deleted, but as new cachings should never lead to duplicates again I don't think such an "auto-cleaning" measure is needed, it would only bloat the code and make everything slower. What you can do is clean duplicates manually if you want, or erase the affected addresses with `address cache ADDR -e`.



If everything is ok please close.
