### ISSUE TITLE
No --debug flag for config set command?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#120]
I've noticed that there is no `--debug` flag for the `config set` command.
Is it intentional?

**Comment by d5000** [comment]
The problem here is that we have a `--delete` command I would like to be possible to use the short `-d` form with.

I have already thought about replacing it with `erase` but I then would like to use this word in all commands instead of `delete`, and in some there are conflicts. I may change that though still.

**Comment by buhtignew** [comment]
Maybe we can chose a letter that doesn't have to do at all with the word debuging, just one that hasn't been used for any command so far, something like `y` or `j`.

**Comment by d5000** [comment]
For now this is not urgent. There are some other commands without debug flag, and there are also no debugging messages displayed at this time, so the only usage for `-d` would be to see the traceback if one of the red errors is thrown. I'll close here and give an update on this topic in issue #7.
