### ISSUE TITLE
the -x and -w compatibility in transaction list command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#140]
Seems like the -w flag is ignored when the -x flag is used with `transaction list` command (for instance in `transaction list  -x -f 480523 -e 480535 -w`).
I was not able to find any hint about in the help. 
_
Maybe it would be also a useful feature to consider (don't know whether for the first release of the code or for the possible next ones), because otherwise to see my own wallets transaction I needed to sort them manually while I was working on issue #139, for instance.

**Comment by d5000** [comment]
For now I have mentioned in the help that both flags are not compatible (for next update).
In theory this could be added probably relatively easily. I'll leave this open and think about it if it's important enough. 

The reason I didn't add it is that I think it would only be important for debugging, because in all other use cases you could use the command without the `-x` flag, and also it's extremely unlikely that you will have all wallet addresses in blocklocator.json. So the main use case would be to see wallet transactions in a narrow range of blocks.

**Comment by d5000** [comment]
This was implemented in commit 77298d5. `-w` can now be used with `-x`.

Help was also updated. Pre-tested, if everything works smoothly this can be closed.

**Comment by buhtignew** [comment]
My `transaction list  -x -f 480523 -e 480535 -t` output is 0, while `transaction list  -x -f 480523 -e 480535 -w -t` is 8.

**Comment by d5000** [comment]
Fixed in commit 8ba2c02. Indeed, the "all transactions" mode was broken by the last changes.

Should now find 15 transactions for the blocks you mentioned.

**Comment by buhtignew** [comment]
Works as expecting.
Closing this issue.
