### ISSUE TITLE
Decentralized swap order book

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#190]
I was thinking about the way for us to have a decentralized swap order book or even a place where the transactions could occur in the privacy-friendly way.
And I think that the possible choice could be the [ssb protocol](https://github.com/ssbc/).
There is a number of projects using that protocol, for instance [ssb chess](https://github.com/Happy0/ssb-chess) or [ssb decentralized drive](https://github.com/cn-uofbasel/ssbdrv/) or even [a p2p social network](https://www.manyver.se/).
So I think it would be possible (in the distant future, of course) to create a place were the users would publish their orders, consult an ordered list of all the offers and contact each other privately to swap their coins and tokens.
It's just an info. I'd like to know what do you think but you can also close this "issue", if you prefer to, without commenting.

**Comment by d5000** [comment]
Thanks for the info. My preference however would be Nostr for this use case, because of the similarities of their accounts with Bitcoin-style private keys. AFAIK people in the DEX, if we use Nostr, could simply use the wallet private keys tied to the address they use for an exchange also as private keys for the accounts they're using for communication exchange, including order books.

If of course SSB has the same advantage then it could be an alternative.

**Comment by buhtignew** [comment]
I don't think it has.
Closing.
