### ISSUE TITLE
token cache testing

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#192]
Both anomalies noticed for the `token init` command in #191 are also present in `token cache` command.

I.e. 
1) by running `token cache -b 100 -a` the output mentions that all the 68 decks will be scanned (and not only those initialized), but as result the fresh `blocklocator.json` file have 97 lines added and none of them seems to contain the addresses of the not initialized decks. 
So it's probably only the issue with the `token cache` output.
2) `token cache -b 100` command seems to check 4 times whether the `blocklocator.json` file exists during the execution, at least in case there is no `blocklocator.json` file in place the message `File does not exist.` is displayed 4 times.

_
I've tested `token cache ATTokenNewSpec2_local -c` and there was the following line in the output: `Start block: 131739 End block: 559804 Number of blocks: 50000`.
So it seemed like instead of scanning the full chain the default, 50k, number of blocks would be scanned. 
However the scanning didn't stop after the first 50k were inspected so probably only the last part of the message (`Number of blocks: 50000`) should be modified.
_
The same command's output has the following line in it: `You can interrupt the scan at any time with KeyboardInterrupt (e.g. CTRL-C) and continue later, calling the same command.`
For those using `pacli_env` the CTRL-C combination would not only interrupt the `token cache` command, but also the `pacli_env` itself, which is not comfortable.
By other hand the above message slightly conveys the idea that somehow the interrupted scanning would restart from the point where the scanning was halted. Or maybe it's just my impression.
However I was wondering whether it's possible to find the way to gracefully interrupt the scanning so as to preserve the results of the scanning done till that point by adding the last analyzed block's hash and the blocks found till that moment into `blocklocator.json`. Maybe there is the possibility to launch a processes along the scanning that would wait for a certain key combination as a signal to proceed with the graceful interruption?
_
I'd also like to ask you whether it would make sense/possible to shorten the scanning process output. I.e. right now if the 50k blocks are being scanned there is a line for each 100 blocks outputted, so as when the scanning is finished there is a lot of lines on the screen. Maybe it would be possible to delete each previous line by replacing it with the next one instead thus displaying that line only?
_ 
There is the following line in the `token cache -h` for the `-b` flag: `Number of blocks to store (default: 50000) (ignored in combination with -f).`
Probably this line has remained untouched since the `-f` flag was changed into `-c` so the `-f` should be edited into `-c` in this line.
_
I don't know whether I've got it right, but it seems like in case of `token cache` is run with the `-c` flag the final block that is being scanned is the highest current block at the moment the command was launched.
However since the blockchain can be quite long, once the scanning is over the current block may be much more ahead, so the `-c` flag wouldn't have performed the full scan of the blockchain.
Would it make sense to make the code re-running the same command once or even more than once again until the chain isn't truly scanned in full? 
_
I've made a complete scanning of the default PoB token. Then I've launched the complete scanning for another PoB tokens (using the  `token cache 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be -c` command).
The deck is not initialized on my side, but there was no message about, maybe it's not necessary in this case.
The scanning has begun from the startblock `132353` since the output reported `First deck spawn at block height: 132353`, although the startblock of the deck is `132000`. So I assume the deck was created with the startblock that had happened before the deck was actually created.
However since the endblock of the deck is `140000` I was expecting that the scanning would stop at that block, which hasn't happened.
Another expectation I had was that the full scanning I've already done for the main PoB token would be enough to consider the scanning for another PoB token also done, since the burn transactions of one PoB token are also valid for all the others. Or at least I thought the scanning process would be much quicker since the goal of the scanning would be to find the relative claim transactions for the burn transactions that are already known.
But maybe finding the claim transactions is the same as just scanning the full chain or this kind of optimization is not a priority at this stage of our work.

**Comment by d5000** [comment]
> Both anomalies noticed for the token init command in https://github.com/slimcoin-project/pacli/issues/191 are also present in token cache command.

#191 was fixed and this should also be not longer a problem here.

50000 blocks shown in the message even with `-c` option was also a small bug, fixed.

> By other hand the above message slightly conveys the idea that somehow the interrupted scanning would restart from the point where the scanning was halted. Or maybe it's just my impression.

Yes, that's the expected behavior. I just tried it and it works this way on my side.

> Maybe there is the possibility to launch a processes along the scanning that would wait for a certain key combination as a signal to proceed with the graceful interruption?

Unfortunately I've no idea how to do this, and I'll also not waste time on it.

`-f` to `-c` flag was fixed.

> I'd also like to ask you whether it would make sense/possible to shorten the scanning process output.

For now I'll put it on standard to 500 blocks.

> Would it make sense to make the code re-running the same command once or even more than once again until the chain isn't truly scanned in full?

Re-running would not be my preferred option. If there's an easy way to do this I can look into it but this is low-priority for me.

>  The deck is not initialized on my side, but there was no message about, maybe it's not necessary in this case.

The P2TH address is not needed to be imported into the node so you can scan all tokens, even non-initialized ones. However, a message should be shown, and in my case it appeared.

> The scanning has begun from the startblock 132353 since the output reported First deck spawn at block height: 132353, although the startblock of the deck is 132000

The deck you mentioned indeed was created at block 132353.

I've tried it with 'testtoken18x9' (25d70b251166fb01d981cf0cfd420417bf3b2447df8c54863db2a1b51c98545f) and it started to scan exactly at the deck spawn block height (552031). So ... is it possible that you had cached the burn address only up to block 132000, so it started at that block?

> Another expectation I had was that the full scanning I've already done for the main PoB token would be enough to consider the scanning for another PoB token also done, since the burn transactions of one PoB token are also valid for all the others.

Only if the deck is significantly newer than the first valid burn transaction, then some time could be saved if you only check the CardTransfer transactions if the burn transactions are already saved.

IMO this however does already work (it should start at the minimum height from the "last cached PoB address block" and the "deck spawn block", but I've to look deeper into it to confirm it.

**Comment by buhtignew** [comment]
>  Is this really worth it?

No please don't waste your time with it.

> However, a message should be shown, and in my case it appeared.

I've deleted my blocklocator.json file and have run `token cache 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be -c`.
There is no hint about the deck not being initialized although `token list | grep 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be` output is the following:
```
| abcd                      | 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be | PoBTokenLimited2          | mvrm2HAoKqiCmeQiwKMuEFpeEn7rJEmpMz | 1 | 458020 |   |
```
but maybe it's not relevant.

From [here](https://github.com/slimcoin-project/pacli/issues/192#temp) on I haven't understood all of your replies, I'm be posting here my comments later, once I'm ready.

**Comment by d5000** [comment]
> There is no hint about the deck not being initialized

In this case your deck should stay initialized, as you only deleted your blocklocator.json. The initialization means that the P2TH address was imported into the wallet file. So it's a bit strange that you don't see the initialization plus sign in the `token list` output. Have you initialized this deck eventually? You can see it also with:

`address list -p | grep 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be`

If it was initialized then you should see a P2TH address with the account name containing the deck ID. In my case the result is:

`|             | mqR3iBYqKprpqjxxZgAtD1jizZxVqc9dh4 | tslm    | 0.07         | 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be           |
`

Can you re-check this?

I'm leaving this open so you can comment on the answers you didn't understand. If everything's clear to you then please close :)

**Comment by buhtignew** [comment]
> EDIT: Decided against this. The problem is that if you store a "limited" PoB deck this way, and later you want to cache a deck which accepts all burn transactions, or even those one block earlier, you would need to re-cache everything, but the way it currently works you wouldn't know that caching is incomplete (for simplicity reasons, the start block is not added to blocklocator.json).

I think I've spotted the issue and it was the cause of me not understanding fully your reply.
If on the blank blocklocator.json you run `token cache -a -b 1000` and then `token cache 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be -c` the caching process will indeed begin from the last block cached by the first command.
However if you run `token cache 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be -c` on the blank blocklocator.json file the scanning will start from the deck's spawn block, `132353`, and not from the beginning of the blockchain nor from the startblock of the scanned deck.

Another thing I've noticed is that if I run `token cache -a -b 1000` on the blank blocklocator.json file again the scanning will start from the first deck spawn block, while there is a number of decks that have startblock equal to None, which means that the scanning should start from the beginning of the blockchain or at least from the first burn transaction of the chain and not from the first deck spawn block.

> (Not sure if still relevant: I've tried it with 'testtoken18x9' (25d70b251166fb01d981cf0cfd420417bf3b2447df8c54863db2a1b51c98545f) and it started to scan exactly at the deck spawn block height (552031).)

I'm not sure what is this section refers to. Maybe you mean that `token cache testtoken18x9 -c` starts from the deck spawn block? If so in my understanding the `token cache testtoken18x9 -c` command should begin scanning blockchain from the very first block of blockchain or from the last scanned block if any since in `token show 25d70b251166fb01d981cf0cfd420417bf3b2447df8c54863db2a1b51c98545f -r` outputs that the startblock parameter is None.

>> However I was wondering whether it's possible to find the way to gracefully interrupt the scanning so as to preserve the results of the scanning done till that point by adding the last analyzed block's hash and the blocks found till that moment into blocklocator.json. 

I've discovered that the graceful interruption is already implemented in the code.
In fact if for instance you run `token cache -a -b 1000` and then during the scanning process send the interruption signal with `CTRL+ALT+c` combination the blocks already scanned before the interruption will be considered cached the next time the same caching command will be run again.
The `CTRL-C` mentioned in the `token cache` output and the `CTRL+ALT+c` combination are basically the same, but maybe it may worth suggesting the later in our `token cache` output because the `CTRL+c` doesn't interrupt anything so there is no way activate the graceful interruption. The difference between the capital and small letter may be not noticed by the user.
In fact I always thought `CTRL+c` was a non-working suggestion in my case and was using `CTRL+z` instead but this combination interrupts the `pacli_env` itself which deletes the command's history.
_
Seeing that allegedly our `token cache` protocol for the PoB tokens makes basically scanning the whole blockchain for all the decks wouldn't it make sense to introduce a flag for `token cache` instead of making the user including some specific DECK in the command?
 _
>>    I'd also like to ask you whether it would make sense/possible to shorten the scanning process output.

> For now I'll put it on standard to 500 blocks.

In bash there is a way to delete a line and to write another line in place of that one, which makes the process appear a bit similar to our waiting process, i.e. as if there was a dynamic change over time.
I understand it's not a priority, so maybe I can move this idea into Nice to have thread, because with the 500 blocks it seems sometimes like the command is stuck and after a full scan the display will be still crowded with potentially useless data while the previous outputs, which may be useful for the later consultation, are gone.

**Comment by d5000** [comment]
> However if you run token cache 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be -c on the blank blocklocator.json file the scanning will start from the deck's spawn block, 132353, and not from the beginning of the blockchain nor from the startblock of the deck.

This should not be the case anymore for PoB tokens. I have just retried it and it starts from 0, also if you enter a list of decks and one is a PoB token.

> Another thing I've noticed is that if I run token cache -a -b 1000 on the blank blocklocator.json file again the scanning will start from the first deck spawn block, while there is a number of decks that have startblock equal to None, which means that the scanning should start from the beginning of the blockchain or at least from the first burn transaction of the chain and not from the first deck spawn block.

This behaviour should also be not the case anymore if there are PoB tokens among the initialized decks. I have rechecked it and it works as expected starting from 0 and printing out the message that PoB tokens will always be cached from 0 (or the last state of the burn address).

> I've discovered that the graceful interruption is already implemented in the code.

Yes, that's already the case since long ago. But the signal seems to be OS/distribution-dependant. In my case I interrupt it with CTRL-c (no shift). That's why I added the "e.g." part.

> Seeing that allegedly our token cache protocol for the PoB tokens makes basically scanning the whole blockchain for all the decks wouldn't it make sense to introduce a flag for token cache instead of making the user including some specific DECK in the command?

But there's already `token cache -a` for all initialized decks? Or do you refer to all PoB decks? Please clarify ...

Regarding the "Processing block" message, the problem is that if I delete a line, this may interfere with debug outputs too. It's a bit more compllicated than just adding the equivalent of `echo -e \rXXX`. So I prefer to leave it the way it is now. I could lower it to 100 again and instead omit the newline, but this can also interfere with debugging outputs leaving them more busy and difficult to process.

**Comment by buhtignew** [comment]
>> Seeing that allegedly our token cache protocol for the PoB tokens makes basically scanning the whole blockchain for all the decks wouldn't it make sense to introduce a flag for token cache instead of making the user including some specific DECK in the command?

> But there's already `token cache -a` for all initialized decks? Or do you refer to all PoB decks? Please clarify ...

I'm referring here to this part of our discussion above:

>> Another expectation I had was that the full scanning I've already done for the main PoB token would be enough to consider the scanning for another PoB token also done, since the burn transactions of one PoB token are also valid for all the others.

> Only if the deck is significantly newer than the first valid burn transaction, then some time could be saved if you only check the CardTransfer transactions for this deck, and the burn transactions are already saved.

> IMO this however does already work (it should start at either the "last cached PoB address block" and the "deck spawn block", whichever is lower). Looked into the code and confirmed that.

From what you've replied to me I've understood that the last cached block of any scanned PoB deck is the starting block of any PoB deck that is scanned next.
For that reason I was thinking that there is no difference between `token cache -a` and `token cache ANY_POB_TOKEN_DECK_HERE` commands from the point of view of the data registered in the `blocklocator.json` file for any PoB deck.
However I've checked things more into depth and now I'm seeing that there is not only the burn address caching involved, but also the specific P2TH address of that PoB token deck.
So nevertheless the burn transactions are being scanned seamlessly even if the caching is being done for two different PoB tokens there shouldn't be any time saving if the scanning process is done on different PoB decks since the P2TH addresses are different and because of those ones the code have to re-scan the already scanned blocks again.
At least it's how I was expecting the scanning process to work.
However my expectations do not seem to be fulfilled if I look into how the code works right now.
For instance if I run `token cache PoB2 -b 1000` on the blank `blocklocator.json` file and then `token cache PoBTokenLimited2 -b 1000` the scanning process in the second case would start from the block 1000 and for the P2TH address of the `PoBTokenLimited2` (`mqR3iBYqKprpqjxxZgAtD1jizZxVqc9dh4`) the startheight mentioned in the `blocklocator.json` file would be 1000, while the last cached block of the P2TH address of the previously scanned `PoB2` deck wouldn't be modified in the `blocklocator.json` file.
So if I run `token cache PoB2 -b 1000` again the scanning would restart from the block 1000.
I'm not sure to know enough about the P2TH addresses, but case of `token cache` command it seems like it works as a kind of bookmark to remember the last block scanned for that specific deck.
However in case of PoB tokens we don't need to have a bookmark for a specific token because all the burn transactions are valid for all the decks so as the `transaction list ANY_BURN_TOKEN_HERE -b -x -l` command would output the same for all of them.
And in the same time because the P2TH addresses scanning begins from the last scanned block of the burn address with this approach we are producing a number of addresses that have a starting block different from 0.
So when I run `transaction list mqR3iBYqKprpqjxxZgAtD1jizZxVqc9dh4 -x -l -f 1 -e 1500` for instance I'm getting `Note: Address mqR3iBYqKprpqjxxZgAtD1jizZxVqc9dh4 was cached from the block height 1000 on.` in the output.
I don't really know whether the caching of transactions for the PoB deck P2TH addresses would be relevant for the users, but if it's not we can consider avoiding caching them at all in the `blocklocator.json` file. While if we need them to be cached the caching process for each PoB token should begin from the block 0.
_
> Regarding the "Processing block" message, the problem is that if I delete a line, this may interfere with debug outputs too.

And what if we try to adopt a different strategy? Instead of outputting the number of scanned blocks we can calculate the approximate ETA and output that one so the user would have a reference to understand whether the command is stuck or just needs more time to scan the blocks.

**Comment by d5000** [comment]
You have partly misunderstood the P2TH address, I think. But I have found a bug which may have added to your confusion. See below.

But first I explain so the misconceptions can be solved.

The first part of your post is okay, you have understood correctly that P2TH addresses are cached additionally to the burn or gateway address.

> I'm not sure to know enough about the P2TH addresses, in but case of the token cache command it seems like it works as a kind of bookmark to remember the last block scanned for that specific deck.

The P2TH address is needed to query transactions of the token itself, i.e. the "CardTransfers". Any PeerAssets token, be it PoB, AT or a "normal" token has a P2TH address.

It is created when the deck is spawned, so we don't need to cache it from block 0 on, but from the deck spawn block on. It is basically a Base58 (the "codification" of legacy Bitcoin/Slimcoin addresses, i.e. 58 characters with letters and numbers) representation of the deck spawn transaction ID.

The P2TH address is however not a "bookmark to remember the last block scanned". The bookmark is the "lastblock" value in the blocklocator.json itself, which is the block hash of the last cached block.

I recommend you to read the original concept if you need more details: https://peercoin.github.io/P2TH/

This is why the current code **should do** the following if you cache PoB tokens:

- cache the burn address: from block 0 or from the last block which was already cached
- cache the P2TH address: from the deck spawn block on

For example, for PoBTokenLimited2 the deck spawn block is 132353, and if the burn address was already completely cached, then the caching for the P2TH address would start at that block.

It doesn't make sense to cache the P2TH address from 0 because like I explained above this address can, according to the laws of mathematics, only exist from the deck spawn transaction on. :)

The bug I mentioned above however did indeed something different: in AT and PoB tokens it tried also to cache the P2TH address from 0 (or from the last cached block in a previous caching session), not from the deck spawn block. This is fixed now.

However, and that's not really nice, the policy means that de facto, the P2TH addresses can then appear to be cached discontinuously, with all the warnings and possible user confusion this implies. One example:

- New blocklocator.json, burn address at blockheight 0
- Cache PoB token A for 10 blocks (`-b 10` option). This means it will cache both the P2TH address A and the burn address from 0 to 10.
- Cache PoB token B for 10 blocks. This will mean now that it will now cache both the P2TH address B and the burn token from 11 to 20.
- Now cache PoB token A again for 10 blocks. It will now cache both the P2 address A and the burn address from 21 to 30. This means however that there is a gap in caching for P2TH address A between block 11 and block 20, and the address will be market as discontinuously cached.
  
This can be solved. But it is an example that a seemingly small change like the "discontinuous caching warnings" can have a lot of side effects. Basically it means that I have two options: 1) suppress the discontinuously caching warnings in the case of P2TH addresses, because there is no harm done in these cases, and 2) make the caching process more complex.

So I think I've violated the KISS principle when adding the discontinuous warning feature. I will very carefully think about adding _any_ new feature from now on, the small it may seem.

I've not commited the full fix still, I need to think about the ideal strategy to deal with the discontinuous P2TH problem.

> Instead of outputting the number of scanned blocks we can calculate the approximate ETA and output that one so the user would have a reference to understand whether the command is stuck or just needs more time to scan the blocks.

An ETA is not possible due to the different processor speeds. But your proposal gave me an idea which can really improve it: we can base the output on percentages of the total blocks to be cached, instead of a fixed block number like 100 or 500 blocks and make it a bit more verbose, also printing a message like in other commands that it can take some time, and also at the first processed block ("0 %") on instead of the first time the command reaches the threshold for the first message.

This is however, _really_, a minor issue (in this case, however, I don't expect side effects, so I will improve it).

**Comment by buhtignew** [comment]
> the P2TH addresses can then appear to be cached discontinuously

When I as testing for my previous post here it seems to me I've checked and there was not discontinuous caching issue, there was only the startblock value issue, because the in case of two decks cached one after another more than once the caching for each deck was beginning from its last block and not from the burn address last block. 
 
> One example

The above example probably works once the startblock of both decks is reached, because if I start from the void blocklocator.json both P2TH addresses are marked as uncached until their reach the startblock value.

> Commit https://github.com/slimcoin-project/pacli/commit/c8cf1c8432687c4d4dd39b30a8b86bfaebfde215 contains the improvement for the progress indicator.

I like the new progress indicator better than the previous one, but at the moment it outputs much more lines than earlier.

> An ETA is not possible due to the different processor speeds.

And what if the code begin gathering caching times on each specific machine the code is being used in order to create reliable local statistics with time?

**Comment by d5000** [comment]
The progress indicator now displays a maximum of 100 lines, this was the main reason for my change (apart from the 0% start message). This can be scrolled in every modern terminal emulator.

ETAs depend on so many factors (current programs running, part of blocks could be cached already etc.) that it is not feasible to give a minimal reliable one. It would also be complex to implement as you would need some stats to be saved in a config file. I will not waste time on this, sorry.

What I can do is to reduce the maximum lines to be printed out to 50 or even 20, but take into account that this comes with a tradeoff: the first progress message after the 0% will then be displayed later.

What I have done now already is to increase the minimum blocks to be processed between each message to 50, so if caching lesser amounts of blocks, about 80% less lines will be displayed. I also improved another issue. Both in commit ec2d359.

I think the other issues are solved with the commits I mentioned in the last post, as far as I interpret your last post, so this issue can be closed.

**Comment by buhtignew** [comment]
Agreed with your position about ETA, the current implementation of the progress indicator works fine, IMO.
Closing.
