### ISSUE TITLE
config show with the -b flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#196]
I've tested the `config show` with the `-b` flag both with the deck as with the address  (like `config show DTNewSpecv2 -b` and `config show  mq1jZAiu8NoL3U3Ed7YiDdfjmY5t6Zphvq -b` for instance) and I was wondering whether it would make sense to move this command into relative `address cache` and `token cache` commands with the `-p` (`--placement` or `--position`) flag. 
Or if (as proposed [here](https://github.com/slimcoin-project/pacli/issues/135#f-flag)) it's possible to move the `-s` flag into the `-f` flag for the `address cache` command then we can use the `-s` flag (as `--state` or `-status`) both for the `address cache` and `token cache` commands.

Another thing I've noticed is that it's possible to use the deck's label but not the address` label. Maybe we can add the address label usage as well?

**Comment by d5000** [comment]
I'll think about it. A `-v` - `--view_blocklocators` option of the cache commands comes into mind which would work without any flag renaming. My thought process is the following:

- advantages of "config show -b": the blocklocator.json file can be seen as a configuration file, and there is less code redundancy.
- disadvantage of "config show -b": a bit unintuitive.
- advantages of an integration into `cache` commands: we can support address labels easier, probably more intuitive 
- disadvantages: more code redundancy

I'm currently leaning towards that change, that would also enable, as I wrote, your proposal to support address labels. I had also considered that option before, but I don't remind why I opted for the `config show -b` option instead.

**Comment by d5000** [comment]
I've implemented it now like announced in the last message:

`address cache -v` and `token cache -v` (or `deck cache -v`) will now show the block locators.

I also added an improvement: I added warnings when tokens were only partly cached, i.e. some addresses were cached and others not.

Commit: ea83d98

Also it is now possible to view address list (the help doesn't reflect this detail in the commit, but it was already corrected, but it is too small of a correction to merit a dedicated commit, will be uploaded later).

Can be closed if there are no further questions.

**Comment by buhtignew** [comment]
> I also added an improvement: I added warnings when tokens were only partly cached, i.e. some addresses were cached and others not.

I was not able to see the warning.
What I did was the following:
- I've picked up a deck for which I've already made caching in the past, specifically DTNewSpecv2
- I've checked its `token cache DTNewSpecv2  -v` and it was the following:
```
Deck not named locally. Searching global deck name ...
Using matching deck with global name DTNewSpecv2, with id: a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a
Result for token a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a:
Block heights: [131666, 131675, 131680, 132512, 132522, 132528, 132625, 132906, 133368, 133372, 133373, 133630, 133632, 133634, 134473, 134475, 134540, 134654, 134656, 134658, 134748, 134750, 134754, 136030, 136077, 136097, 136099, 136254, 136256, 136258, 136592, 136594, 136596, 136627, 136629, 136631, 136646, 136674, 136676, 137290, 137292, 137298, 137300, 137630, 137632, 137634, 137636, 137854, 137856, 137938, 137940, 137972, 137974]
Last commonly checked block (hash): 00000007dba93eadfabb2722955aa0885a4d0f424ebce87a41e6db3a5dd93a0b
Last commonly checked block (height): 181639
```
- I've checked the P2TH addresses of that deck, using the `token show DTNewSpecv2 -r -s` command, here is the relevant part of the output:
```
'_p2th_address': 'mxasNazVpdfTmjQcedfxtHQtb3NXKVGEzh',
    'derived_p2th_addresses': {
        'proposal': 'n1WEs2vcEbXFQWe6GtsFgHfQmzavHVYMi4',
        'signalling': 'mgiYjQjREbtKcKKH1kFXo1ycWCfGB5aZd7',
        'locking': 'mqZ5nqs6bpaAqEoEV9jVFfwsM3hBZD4C3J',
        'donation': 'mzP9BNtqjSNq2rJ58w8GpQNnez38NGagsU',
        'voting': 'mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym'
```
- I've picked up one of the above addresses, specifically `mgiYjQjREbtKcKKH1kFXo1ycWCfGB5aZd7`
- And have run partial caching on that address, using `address cache mgiYjQjREbtKcKKH1kFXo1ycWCfGB5aZd7 -s 589000 -f` command. The output was:
```
Storing blockheight locators for addresses: ['mgiYjQjREbtKcKKH1kFXo1ycWCfGB5aZd7']
Forcing to cache block heights as required. Last stored block was 181639, continuing from block 589000 on.
Processing block: 589000
You have reached the tip of the blockchain.
Stored block data until block 589447 with hash 0000002591f5ce606800af3da92e7108ab7808eed4e50e58e3623e0fee1b7b64 .
Block heights for the checked addresses: {'mgiYjQjREbtKcKKH1kFXo1ycWCfGB5aZd7': [134654, 134656, 134658, 136097, 136592, 136594, 136596, 136646, 137854, 137856]}
```
- Then I've run `token cache DTNewSpecv2  -v` but got no error message. 

Maybe it's because new block was found for that address?

**Comment by d5000** [comment]
The warning indeed is only shown if there are block locators found for some addresses but other addresses are either uncached or their last cached block height is below the last block height where locators were found.

The "official state" of the token's block locators is always at the block shown as "last cached block", which is the minimum block height of all addresses.

There is also a warning in red when at least one address was completely uncached.

If the user however caches some addresses of a token discontinuosly, and there are no locators found because of this discontinuous caching, there is indeed no warning. I think this is what you tried.

An example where discontinuous caching can lead to misleading results:

Address A has transactions on block 200 and 500. User caches the address up to block 150 and then again from block 1000 to 2000, for whatever reason. So the caching "state" ("Last cached block") of this address becomes 2000 but no locators are found because there were no transactions between 0 and 150 and between 1000 and 2000. However, there "should" be locators on blocks 200 and 500 obviously.

Then the user uses A as a gateway address for an AT token.

Now, however, the P2TH address is generated from the deck spawn transaction. This means that it will be uncached.

So if the user, even with the mistake he made due to his discontinuous caching, uses `token cache` to cache the rest of the addresses (in this case, only the P2TH address), the process currently will start again at the genesis block. [1] The locator block heights missed by the caching process of address A (when the user only cached the address incompletely) thus will be found and once block 500 is cached the state is again correct.

So at least if the user begins to cache the token and not invididual addresses only, the state shown will be correct in this case. This is also a reason why I'm not allowing discontinuos caching for tokens.

I'm wrapping my head a bit about this, if there are situations where more warnings may be pertinent. Tokens where only a single address (often the burn address) will be cached at the first time an user uses `token cache`, are a result users will see often when they use the block locator commands correctly, so here I'm willing to optimize it.

**Comment by buhtignew** [comment]
I think I've understood all, so we can close this issue unless you'd prefer to keep it open as reminder about the optimization you've mentioned above.

**Comment by d5000** [comment]
I'm closing as there is a new issue open about discontinuous caching which addresses the last remaining "problem" more precisely.
