### ISSUE TITLE
transaction list -b -u and transaction list -b -u -w comparison

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#201]
The output of `transaction list -b -u -t` on my side is 29, the output of the `transaction list -b -u -w -t` is 27.
Considering the issue #199 I was expecting they would differ by 3, but the `5a495f4c93bd253a0af1920ab2899583f629045832392b1d0ea85c56db37d13c` transaction is not included in the `transaction list -b -u` output, while `3aea75c2011e15a75454a01c963eb6d26ebb8b62f39abc9e8428458a9b5290e8` and `779c17983503f4d236fd192fdd12e4571d2f94922da59b8a4df8ddd5db3d055f` are.

**Comment by d5000** [comment]
Which deck are you using here?

**Comment by buhtignew** [comment]
I was assuming the default deck would be used in case the DECK is not mentioned, but from the help it seems like DECK is mandatory in case of the `-u` flag.
However if I run `transaction list -b -t` and `transaction list -b -w -t` I'm getting 70 and 67, so the `-u` flag is not completely ignored in case of the `transaction list -b -u -t` and `transaction list -b -u -w -t` commands.

**Comment by d5000** [comment]
> However if I run transaction list -b -t and transaction list -b -w -t I'm getting 70 and 67, so the -u flag is not completely ignored in case of the transaction list -b -u -t and transaction list -b -u -w -t commands

Don't get your logic here :(

`-b -u` without deck (either with or without `-t` and `-w`) throws an error message, and this is the expected behaviour, as the `--unclaimed` flag only makes sense together with a deck.

The differences you spotted among versions with `-w` and without `-w` can be explained in two ways:

1) the issue I addressed in issue #199 (those related to the address finishing with ...Zdya). This should however now no longer be the case, as posted there.
2) if there are transactions not sent from your wallet, but with an output received by your wallet.

Only if both aren't the case then there can be a bug.

My guess is that #199 should also have solved this one.

> It seems like transaction list doesn't output any error in case of two identical global labels: for instance if I run transaction list my_first_pod_deck -b -u  -t it picks the deck 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7 so the other deck I have with the same global name is ignored.

Just re-checked this. I had a deck of this name stored locally, and no error was shown. But when I deleted the label, then the command aborts -- as expected -- with the error: `Error: Deck global name ambiguity, please use the deck's id or its local label.`.

So is it possible you have stored that label locally for that deck?

**Comment by buhtignew** [comment]
> Don't get your logic here :(

I apologize, I don't really know what I meant in this case.

> `-b` `-u` without deck (either with or without `-t` and `-w`) throws an error message, and this is the expected behaviour, as the `--unclaimed` flag only makes sense together with a deck.

Now it's throwing the error, but it wasn't throwing it previously on my side, that was probably the reason I've opened this thread.


> So is it possible you have stored that label locally for that deck?

Oh, my! Of course.
_
All the other questions mentioned in this thread are solved.
I'm closing.
