### ISSUE TITLE
transaction list with dPoD tokens

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#202]
It seems like the `-u` flag in case of the `transaction list` command can be used only together with the `-b` flag.
And also the `-c` flag can be used  for the AT/PoB tokens only.

So I was wondering what is the tool to list the unclaimed and claimed tokens in case of the dPoD tokens.

**Comment by d5000** [comment]
`-c` normally should work for dPoD too, if not then it's a bug.

For me it works with token DTNewSpecv2 (the "official" dPoD token a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a) and with dt_short (3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c).

Regarding unclaimed transactions there's no direct equivalent, because we have no mode in the transaction list command which shows all dPoD donation transactions. However we have `donation list DECK -m -u [-w]` which does the same thing for the own wallet.

When looking at that command I discovered one bug in `donation list DECK -m -u` (which made the -u flag not work correctly in all cases) and fixed it. 

The only mode missing until now was a mode where you could see unclaimed transactions of all donors. I noted that it was easy to add with a minor change in the way the arguments are processed. I've updated the help so you can see how the flags are used now (only major change is that `-p` is required now always if you limit the transactions to a proposal).

Commit is bd9ac14. It needs no further testing.

All dPoD related issues anyway will be on hold until the PoB/AT token and DEX/swap parts are finished and unittested.

**Comment by buhtignew** [comment]
I'm closing this.
For the moment the dPoD token is on hold on my side as well, so I'll begin testing all those commands once we've done with the PoB tokens and with the swap group of commands.
The only thought I had is whether it would make sense to let people see their unclaimed dPoD tokens with the `transaction list` as well, but TBH I wouldn't like us to add further work since we've done more than enough at the moment.
