### ISSUE TITLE
Would it be possible to align the results of transaction list DECK with -b, -c and -g flags?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#208]
I've just realized that the `-w` flag has a different meaning if used in context of `transaction list DECK -c` command compared to `transaction list DECK -b` command.
In fact in the later case the `-w` flag just excludes the P2TH addresses, since the `-b` flag already shows all the wallet's transactions.
On the opposite in case of the `-c` flag the `-w` limits the output to the same degree as the `-b` flag in the other usage mode, but doesn't exclude the P2TH addresses.
This is because, unlike the `-b` flag, the `-c` flag doesn't show the claim transactions of the wallet but all the claim transactions of the net, so it's somehow more similar to the `-x -l` flags (i.e. explorer mode).
Since we don't practically have any letter left to be used as a flag I don't dare to propose splitting the two functions of the `-w` flag (something like "exclude P2TH addresses" along with the `-w` flag to be used with the `-c` flag while the `-w` flag wouldn't be useful in case of the `-b` flag should we have "exclude P2TH addresses" flag), but it's something we should somehow keep in mind, because the subtlety of the current set up is a bit difficult to grasp.

**Comment by d5000** [comment]
> On the opposite in case of the -c flag the -w limits the output to the same degree as the -b flag in the other usage mode, but doesn't exclude the P2TH addresses.

This should not be the case. Also in the `-c` mode if combined with `-w` the sender must be in the wallet and cannot be a P2TH address. I've just re-checked the code and it should work normally.

If this is not working for you and any P2TH address is shown when you run that command, please provide the deck and the txids which were sent by P2TH addresses or non-wallet addresses.

>  unlike the -b flag, the -c flag doesn't show the claim transactions of the wallet but all the claim transactions of the net, so it's somehow more similar to the -x -l flags (i.e. explorer mode).

This is correct, because claim transactions are always in the wallet once the deck is initialized, so they can be shown without needing the explorer mode.

So basically, the wallet mode should normally work the same in all cases, but it's correct that the "standard" modes (without `-w` nor `-o` ) work different.

For `-g` this will also not be possible to change because a gateway address is just like any other address and thus it's impossible to import it into the wallet without importing the private key (as long as we don't have watchonly addresses).

For `-b` I initially thought all burn transactions should be stored locally (and shown by the command), but I see at least for `transaction list -b` they aren't shown all (I have edited the help to reflect this): only those that "touch" your wallet in some way. I however think there must be a way to access these transactions (without accessing the blockchain), because the client needs to know them to validate PoB blocks.

I'll continue to investigate the latter case, if I can access the non-wallet burn transactions, then I'll change the command in a way it shows all.

**Comment by buhtignew** [comment]
> If this is not working for you and any P2TH address is shown when you run that command, please provide the deck and the txids which were sent by P2TH addresses or non-wallet addresses.

You are right there are no P2TH addresses shown in case of `transaction list DECK -c -w` command.
So the output of the `transaction list DECK -b -u -w` + the output of the `transaction list DECK -c -w` is equal to `transaction list DECK -b -w`.
However if I've got it right the `transaction list DECK -b` and `transaction DECK -c` provide results of two different realms:
- `transaction list DECK -b` outputs the wallet's burn transactions + the burn transactions (if any)
from the P2TH addresses of the initiated decks,
- `transaction list DECK -c` outputs all the claim transaction of that deck, for all the users of the net.
So the output of these flags seem to be non-aligned.

I was thinking that maybe when someone uses the `-c` or the `-b` flag they are looking first of all for their wallets info.
And that usually the P2TH addresses results are not of their interest.

So what if we provide the current `transaction DECK -b -w` result just with the `-b` flag alone and the same for the `-c` flag?
In such a case the `-w` flag would be transformed into `--with_p2th_transactions`, in case someone would need them.
While the current output of the `-c` could be moved into `-c -x -l` flags combination or just into `-c -x` (although there is no real scanning performed on that data).

Of course if you find the way to retrieve all the burn transactions of the net then we can align the `-c` and `-b` flags in the other way, i.e. both would show all the relative transactions of the net, but still there would be the issue with the `-g` flag that would remain non-aligned.

**Comment by d5000** [comment]
I'm leaning against that change for the following reasons:

1) the wallet flag is straightforward and also used in some other commands, also it is now compatible with the `-x` mode; we would then also have to change the flags of the other `transaction list` modes,
2) the wallet flag is a restriction, i.e. without the flag the command will show more transactions and is also faster in several modes,
3) above all with `-c` and perhaps `-b` (I've to investigate this, as I wrote before) it is possible to show all transactions of that type.

I understand however that the advantage/difference of `-g` alone versus `-g -w` (and currently also `-b` vs. `-b -w`) is currently very small. My idea was however to improve the standard mode later when we get watchonly addresses (this is a change which perhaps can even be done before the "big update" to newer Bitcoin code, as Graham Higgins had already published an alpha with this feature but something went wrong and he abandoned it), in this case we can use this flag to show all gateway transactions of a certain token.

**Comment by buhtignew** [comment]
I don't think it's relevant at this stage.
I only think we have many different levels of data outputted by these flags and they are not aligned, but maybe we'll align them in the future, like you said.
I'm closing this for the moment.
