### ISSUE TITLE
`config list -e -c [CATEGORY]` proposal

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#22]
I think it would be comfortable to be able to select only the content of one category using the command mentioned in the title.
Since there is much information in `config list -e` output, being able to list only a part of it would be comfortable.
For instance `config list -e -c deck` would list only the info of the deck category.
Would it make sense for you?

**Comment by d5000** [comment]
I had briefly thought about this, but discarded it because it is normally covered by the `--named` options of the other `list` commands.

For example `transaction list -n`, `address list -n`, `checkpoint list`.

In my view this would be a innecessary redundancy, as all categories have this kind of commands.

Taking into account this, would you still think it could be an improvement? Priority would be low but I would not outright oppose it.

**Comment by buhtignew** [comment]
I haven't thought about it from that prospective.
In fact it's the same info. And if the `-q` flag is added then the output looks even more similar.
I'd say my opinion about this idea is somewhere between "not necessary" and "nice to have".
So I'd say if we decide to implement it we should consider this task as a very low priority.
I'd say we can close this issue.
