### ISSUE TITLE
`config set` tests on basic configuration file

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#24]
I've tried to change each value mentioned in the `config list` output.

If useful here are my discoveries:

- changing the `network` value is critical, after the change I'm receiving a `UnsupportedNetwork` exception;
- changing `production` to `False` doesn't seem to be critical at least from the point of view of `config list` output;
- `deck_version` value change doesn't seem to be critical;
- `change` not critical for `config list` output, but most probably critical for receiving the change :-)
- `provider`, `rpcuser` and `rpcport` - critical for `pacli`.

**Comment by d5000** [comment]
> deck_version value change doesn't seem to be critical;
> changing production to False doesn't seem to be critical at least from the point of view of config list output;

Both values, if changed, do not prevent pacli from working, but will lead to very weird errors later.
For example, if you want to deal with a deck and have "production" changed to False, it will most likely not work because the production value is used as a filter when decks are searched by PeerAssets. With production set to False you can create test decks which do not clutter the "production" deck list (sort of a "PeerAssets testnet").
The same applies for the deck version.
And your assessment about "change" is correct, however you can change it to any of your addresses if you want and it should work. I have tested that a long time ago but should "refresh" my memory a bit for this setting ...

**Comment by buhtignew** [comment]
I think this info should be clear for the user before he changes those values, as well were to go to change the critical ones manually if needed (pacli.conf).
So maybe this issue can be useful for you when implementing Yes/No dialog mentioned [here](https://github.com/slimcoin-project/pacli/issues/12#issuecomment-1951417281)?

**Comment by d5000** [comment]
I added a note to the help and also added the y/n continuation confirmation in commit 9e1f00c.

I guess this can be closed.

**Comment by buhtignew** [comment]
Great, it works.

I have some issue with pacli_env, though.

When I run `config set network tsslm -r` for instance and then reply yes or no in both cases my pacli environment crashes with the following output:
```
esrlwrap: main.c:477: main_loop: asserzione "!always_readline" non riuscita.

rlwrap: Oops, crashed (caught SIGABRT) - this should not have happened!
If you need a core dump, re-configure with --enable-debug and rebuild
Resetting terminal and cleaning up...
```
What is different in case of yes/no dialog compared to the normal pacli interaction?
Is there any kind of output for instance?

**Comment by d5000** [comment]
I'm afraid I can't help you much with that issue.

Anyway, if it helps you: The yes/no dialog uses a python input() command. This one indeed catches the input in a different way that if you enter a pacli command because obviously the interaction occurs inside the Python function, not at bash level. So that may have led to your issue. I have no idea how rlwrap works however.

 There is only output if you don't enter 'yes' ('Aborted' is shown). 

However, I have tried pacli_env myself with the command and didn't get that crash.

**Comment by buhtignew** [comment]
Ok then.
I'll need to work on this by myself.
Let's close this issue.
