### ISSUE TITLE
`config list -l` option

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#25]
I think I've already mentioned this topic [here](https://github.com/slimcoin-project/pacli/issues/12#issuecomment-1944701298), but I'm not sure what was your reply about.

Right now I've tried to change the value of the additional LABEL visible with `config list -a` command, so I've run `config set testnet False -r` and got the following output:
```
Error: Invalid setting key. This label doesn't exist in the standard configuration file. See permitted labels with: 'config list -l'.
```

Should we change the output of `config set LABEL VALUE -r` for additional labels of the basic configuration file or you are going to implement the `-l` flag in `config list` analogous to `-c` flag for the same command that would output the list of modifiable basic configuration file values later on?

**Comment by d5000** [comment]
I think you mean this was talked about in issue #23 . These values can't be changed as they aren't stored in the basic file, they are loaded each time pacli is started (i.e. with each command).

So I don't quite understand your question, which `-l` flag do you mean? Something like `config show -l/--label`? `config list -l` would make no sense as it would display exactly the same information than `config show -l` (which can have several matches if there are exact values).

**Comment by buhtignew** [comment]
The idea was to introduce a `-l` flag for `config list` in order to output all the labels of the basic configuration file which values can be changed.

**Comment by d5000** [comment]
For me the keys of the dictionary which is printed when you hit `config list` is enough, because the basic config file is quite ... basic ;) (there are currently 8 "labels"/settings entries).

If you think anyway that a option showing only these 8 labels would be an improvement I can implement it but I personally don't see a necessity here.

**Comment by buhtignew** [comment]
I think there should be some hint on what can be edited and what is not.

Maybe we can put it in `config list` help for the `-a` flag, saying that only values of the basic setting outputted without this flag are modifiable.

**Comment by d5000** [comment]
I saw now why you got confused, as there is no `-l` option on `config list` but an outdated error message (the one shown when you try to edit a setting with non-existing label) mentioned this option. I changed it so that you instead should consult `config list`. I also added to the arg description of `-a` that these settings can't be changed.

Can this now be closed?

**Comment by buhtignew** [comment]
Thank you very much!
Now it seems to be more clear to me.
We can close this issue.
