### ISSUE TITLE
deck's names/labels ambiguity

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#28]
I've discovered an ambiguity about the names of the decks mentioned in `deck list` output:
Those names are of course not labels, but I've realized it later on when I've tried to test `transaction list DECK_LABEL -b` command.
Maybe we can change the column `name` into `name(your label)` and output the label chosen by the user in brackets, along with the deck's name?

**Comment by buhtignew** [comment]
> In the last commit https://github.com/slimcoin-project/pacli/commit/02dd18b90711cf45668535f20501307efe46db7d (which also fixed the error message for transaction list -b) I changed the behavior of the -n/-named option of deck list. Now (local) labels and names are shown in different columns.

I feel it certainly as an improvement, but since we call our labels also "names" the source of ambiguity seems to be still around the corner.

The distinction here is between the global name and the local label, but the user may forget to have given that label to a deck which may cause him some stress by using the global name instead of the label or vice versa, receiving error messages he may not be able to understand for a bit.

I've tried to find the wording to distinguish this two concepts (global and local names) even more, but was not able to.

So I've went up with the following idea:
What if we keep the global name as default one until the user doesn't name the deck with its own label?
Once the label is given (and until it's not deleted) the default name is the local one.
The global name can be still consulted using the specific flag, but instead of providing both the default one will be outputted everywhere the deck's "name" (or "label") is mentioned.
This would also provide the user with the tool to "fight" the same global names for the different decks, which is by now hasn't been managed by us, if I remember well.

> ...although this would break compatibility with the original PeerAssets vanilla command (anyway, we have broken that already with config set...

Breaking compatibility sounds scary to me.
1) Was it because of my insistence that we've broken it in case of `config set`? 
2) What should be done to restore that compatibility?
3) What could be done to avoid breaking the compatibility for the `deck list` command?

**Comment by d5000** [comment]
>  What if we keep the global name as default one until the user doesn't name the deck with its own label?

I've thought about that but there is a problem: global names are not unique. If that wasn't the case we could probably get rid of the labels for decks completely.

I have also fears that showing two different variables as "name" only according to an user's decision could only lead to more confusion.

So I think it's best to simply accept that there is a "Global name" and a "local name" which may be different, and highlight the differences between both in manual, tables etc..

So my proposal is only a little bit different than yours :) 

1) When 'deck init' is called, the default behavior is to store the global name as local name. If there are several decks with this name, above all if the deck is not the first which was named (globally) this way, then the user could be warned. `deck set` could also have the same default mode, i.e. store the "global" name as local one.

2) in the `deck list -n` table put "Global Name" and "Local Name" as different column headings, like now but with the new terminology ("label" would then not be used in this case). So if there is any difference it's still clear which name is which. This terminology should also be applied to the manual.

----

About `config set`: No, this time it was me, just because of the fears of the user breaking something, and also due to consistency, I've added the `-r` flag as mandatory. It could be simply defined that the `-r` flag is not mandatory for the standard file, but if we want full compatibility, e.g. for scripts, we'd have to remove the Y/N confirmation dialog too.

`deck list` is currently compatible with vanilla PeerAssets. It would be incompatible if we add the local name to the default table (the table shown when the user uses `-n` is not affected by this because vanilla PeerAssets has no `-n` option of course).

It would be perhaps a still reasonable change if we change the heading of the default list to "Global Name" instead of just "Name". It would still behave in a way a vanilla PeerAssets user would expect.

**Comment by buhtignew** [comment]
> So my proposal is only a little bit different than yours :)

I like your idea.

> ...but if we want full compatibility, e.g. for scripts, we'd have to remove the Y/N confirmation dialog too.

I think the answers to the Y/N dialog can be automated as well, with `echo "Yes" | [command_with_Y/N_dialog]`, for instance, at least I have different scripts that do that.

**Comment by d5000** [comment]
> I like your idea.

Great, I'll implement it then.

I've just got a general idea about compatibility, because I don't like the idea to have to remove user-friendly elements like the Y/N dialog, nor to make the commands incompatible with vanilla:

We could add a setting to pacli.conf which sets a compatibility mode. If this mode is set to True, then the few commands which are not fully compatible to old PeerAssets (currently, imo it's at most a handful of commands) could work so that it remains fully compatible, and for example would continue to show "Name" in the `deck list` table instead  of "Global Name". and the Y/N dialog in `config set` would not be shown. Default would however be the not-fully compatible mode which would be more user-friendly.

This would not be much work (at most an hour in total), almost add no complexity to the code, and would be a "final" solution for all compatibility issues. We could then be much freer in changes to the interface, although we still should follow the goal to keep most commands compatible.

If you like this idea I'll implement that too.

> I think the answers to the Y/N dialog can be automated as well, with echo "Yes" | [command_with_Y/N_dialog], for instance, at least I have different scripts that do that.

The user could simply use `-q` mode to bypass this. The point is however to make the command compatible with scripts written for vanilla PeerAssets. I think I should try to achieve that, and the compatibility mode would provide a solution for that problem.

**Comment by d5000** [comment]
The `deck init` change using by default the global name as label is implemented as of commit 59dae5a.

I'll leave this open because the compatibility mode is still not implemented.

**Comment by buhtignew** [comment]
> When 'deck init' is called, the default behavior is to store the global name as local name.
Did you mean that in absence of local label the global name could be used in the command like ` transaction list [deck_name] -b`?
If so would it be possible to implement the command in the way that the both the local label and the global name could be used for this command and for all commands that uses the deck_name?

**Comment by d5000** [comment]
No, it works only if the global name has been saved as a local name.

I don't want to implement the global name as an option for `transaction list` etc. because of the problem that deck global names are not unique.

In the current configuration however always if the deck is initialized the system tries to store the global name as a local name, so "de facto" the user would be able to do this in most cases.

**Comment by buhtignew** [comment]
> In the current configuration however always if the deck is initialized the system tries to store the global name as a local name, so "de facto" the user would be able to do this in most cases.

Great feature, I've tested it right now and will post a question about in another issue.

I think this feature is what we need, but there should be something that let the user easily find out which decks are initialized and which are not.

I remember we've spoken about do we already have such a tool already?

**Comment by d5000** [comment]
No, this is still not implemented, but this is a feature I find useful too and is not difficult to add so I'll implement it asap. It would be a new variant of the `deck list` command.

**Comment by buhtignew** [comment]
I was thinking we can just an `*` to the name in the `deck list` output but I'm not sure about since people may think that the name includes the asterisk.

**Comment by d5000** [comment]
I've implemented the compatibility mode in commit 3df2457. In issue #41 I describe how to enable/disable it and what it does as of now.

This also allowed me to add the initialized status to `deck list`, and also the local labels to the standard view, if the compatibility mode is set to False. A more basic view without initialized status is available with `-b` option.

However, the table is now a little bit wide (up to 188 characters in my view, and it could be even wider depending on the label/name length). I'll consider your suggestion with the asterisk, although I don't consider it ideal, for the same reason than you: it could be considered part of the name, and PeerAssets actually allows deck names with asterisks which I could confirm. Perhaps I can optimize the table width a bit still, but not by much.

**Comment by buhtignew** [comment]
We can explicitly prevent people from creating names with asterisks and in case the asterisk is part of the name it's treated as no character at all, for instance `deck**4* *` is `deck4` for instance.
Don't know whether it may make sense, though.

**Comment by d5000** [comment]
No, I would oppose that, because you can always create such a deck spawn transaction manually. Making such decks invalid would interfere too deeply with PeerAssets' inner workings, and stripping characters from the table would create new ambiguities. Anyway, this column is not the one which makes the table really wide (we can strip it down to 3 characters width), it's mainly the label column.

For now, I think I'll optimize it a bit and leave it mainly as it is.

**Comment by buhtignew** [comment]
Agreed.

I think we can close this issue.
