### ISSUE TITLE
address get_unspent command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#43]
I've tested `address get_unspent` and with any amount I'm getting the same transaction in output:
```
{
    'UTXOs': '03d0afd6370c275b99c107699e00a511401ec46af980ed823593fadc59c5f866'
}
```
Update: for the different addresses the transaction id is different, but the same for any amount I use with the `address get_unspent` command.

_
There is also the following line in the help

```

NOTES
    You can also use flags syntax for POSITIONAL ARGUMENTS
```
Is it appropriate in this context? (It seems like there are no flags for this command).

**Comment by d5000** [comment]
Uh, this is one of the vanilla commands. I've looked at it and it does not even take into account the "amount" you enter.

What it does actually is to show if you have an UTXO in your address from where you can pay the fees for a PeerAssets transaction (0.02).

I have changed the help string and removed the "amount" argument (commit adb69c7). I'm probably reworking this command because I have some own functions which do something similar, or disable it entirely.
