### ISSUE TITLE
Named p2th address included into address list output.

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#49]
I've discovered that the p2th address with a label is being included into the`address list` output.
Specifically the address `mqZ5nqs6bpaAqEoEV9jVFfwsM3hBZD4C3J` was labeled by me with `no_transactions?` label when I've discovered that it has no transactions and I can see it in my `address list` output.
_
By comparing the output of `address list` and `address list -p` I've discovered the possible new p2th addresses that weren't [in my list here](https://github.com/slimcoin-project/pacli/issues/5#issuecomment-1925401543) originally:
`n4HXAq2XjJAt4cNRL9gpPjDS7r8hxmghVR`
`mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn`
`mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik`

I can see that the last 2 have been however mentioned in the issue #5, but not in my original list, while the first one haven't.

Has this address been created somehow later on or it was there, but not listed by any command we've run while testing, for some reason? Or it's an address of a different category, not the p2th? 
_
There is also an additional list of addresses that are present in `address list -i -p`, but are not present in `address -i` output:
`mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH`
`mmjaHuS1kTRMFJaTJqYMjdmF18n36eXHfD`
`moDgh2HgPZKWpFrNesC4QVBzvBrV79p9pA`
`mp5zpXDLxTn24XPai5BX1mkd2XZxhAwxfe`
`mqnBdCH2cuoSiQWjKoEZHfov77bzrpmtNX`
`mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211`
`muhhYam1NXMSUqKx4uSrfjS7N7Fcz6j6Qx`
`mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym`
`mxfu9BNbsaECVVBRiqzavcvp6xhB2cz9r8`

I'd say it's void p2th addresses if it were not for `mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym` which has 0.1 SLMs on it.

**Comment by d5000** [comment]
Named addresses are always included in address list if they're in the wallet, be them P2TH or not. This is intended behaviour.

"void p2th addresses" with balance 0 can exist. If you create a new deck but do not create nor move any tokens, and then initialize this deck, then they are still "registered" in your wallet (i.e. assigned to an account).

Also, if you initialized any new deck since you saw your old list, there will of course be new p2th addresses in the -p output.

I've checked some of the addresses of your list (not all) and they were in my -p output too, so they are almost for sure P2TH addresses.

However, for example mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH has a balance of 0.16 tSLM in my list. Do you see that too? If not, there may be a bug, or you may have to rescan.

**Comment by d5000** [comment]
> The mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH address has zero balance on my side.
I have looked what deck this P2TH address comes from and it seems to be a signalling tx P2TH from an old deck which is now invalid (deck id: 3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c).

Remember the `transaction list`/`address list` bug which took me so long to fix? It's likely you had initialized this deck with the old method before the fix I applied, so now it still has this bug.

I would suggest you to re-initialize all decks, so we don't lose time with these errors which have their roots probably still in your corrupted wallet file. Or simply create a new fresh wallet, which would be even better. I can send you testnet coins if you don't want to send some from your server. Of course you have then to re-initialize the decks again.

(The keyring and extended config file would not be affected at all if you create a fresh wallet)

However, please wait with initializing until I have tested the new features in `deck init` (I'll open an issue soon about "block explorer mode", and deck init has now a new feature to already scan the transactions of some decks) so we don't run into unnecessary bugs.

> Assumably their difference should consist in the void p2th addresses only

There's a misunderstanding here, I think. The difference between both command flag (-i -p versus -i only) combinations should be all P2TH addresses, be them "void" or not. `-i` does not mean that there are void addresses only, it means that the empty addresses are included alongside those with balance. So in the difference between both commands there will also be P2TH addresses with balances. But the command behavior has anyway changed, see below.

> Maybe we should change the output of the address list -p and show only the p2th addresses

I think this makes sense, so I implemented it (commit cfed960). The table does not show any tokens now for these addresses, instead the account, which gives hints about the deck and its function.

**Comment by buhtignew** [comment]
> The table does not show any tokens now for these addresses, instead additionally it shows the account, which gives hints about the deck and its function.

Great!
Seems that there is a column missing at the end of the table: there are words like DONATION, SIGNALLING, PROPOSAL and so on attached to the P2TH account id, like this:  `a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765aLOCKING`.

I also think that the named P2TH address shouldn't be included into the basic `address list` output, because named or not those addresses are not "mine".

> Or simply create a new fresh wallet, which would be even better.

I would prefer to try initializing all the decks first, because I have lot of different kinds of transactions already on my wallet which gives us much more testing material, thus potentially helps finding out more bugs.
Isn't there a command to reinitiate all the decks at once, by chance?
Is it possible that I basically haven't initialized the relative deck of that transaction and for that reason the balance is zero at my side?

**Comment by d5000** [comment]
> Seems that there is a column missing at the end of the table:

No, this are the actual account names (the PROPOSAL etc. is part of the account name)

> I also think that the named P2TH address shouldn't be included into the basic address list output

Disagree. You should have a short command to see all the names you gave to addresses. If you don't want to see P2TH, then you can use the normal output. I doubt also many users would give names to P2TH addresses.

> Is it possible that I basically haven't initialized the relative deck of that transaction and for that reason the balance is zero at my side?

Exactly. Did you try to initialize the deck I gave you (3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c)? What happened? It is possible that you afterwards have to rescan for the balance to be shown correctly, and maybe even restart one more time.

I'm hesitant to add an "initialize all decks" option for a simple reason: it's likely that if PeerAssets on SLM is even moderately successful there will be hundreds or even thousands of decks eventually, and those using this command will then have a lot of accounts in their wallet and a very slow command. But you can simply use `deck list` (with compatibility mode off) and then initialize those which are not shown as initialized. Those shown as initialized are already using the "new" method.

If deck 3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c is shown as initialized before you initialized it, then it's not working as intended but very likely it's still caused by your partly corrupted wallet file. I can then look into the file you sent me.

As I wrote, in my case the deck is initialized and the address mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH is showing the correct balance.

**Comment by buhtignew** [comment]
The deck `3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c` is initialized on my side.
Should I initialize it again or scan or both?

> I'm hesitant to add an "initialize all decks" option for a simple reason: it's likely that if PeerAssets on SLM is even moderately successful there will be hundreds or even thousands of decks eventually, and those using this command will then have a lot of accounts in their wallet and a very slow command.

You are right, it doesn't make sense implementing such a command.

> Disagree. You should have a short command to see all the names you gave to addresses.

I think the `address list -n` could be such a command, while the `address list` and `address list -i` could include the actual user's addresses, while the `address list -p` and the `address list -p i` would be specific to p2th addresses.
I don't insist on my opinion. I agree with you that we should not focus on questions that are not that important at this stage.

**Comment by d5000** [comment]
I have tried your wallet file now and re-initialized the deck 33.. . mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH showed initially 0 coins, while the other P2TH addresses you mentioned before (mmjaHuS1kTRMFJaTJqYMjdmF18n36eXHfD etc.) do show a balance. However, after a rescan and another start it showed the correct balance.

So yes, please shut down the client, start with `-rescan`, and then restart the SLM testnet client once more, and then it should work. If not, I think you should really create a new wallet file to avoid further confusion.

Please do the same any time if the same problem appears again (a P2TH address not showing the balance I get on my side) - re-initialize deck, restart with `-rescan` and then restart again. The "double restart" is sometimes necessary and sometimes not, I haven't figured out why, but it is possible SLM does only modify its wallet file according to some kind of schedule and not directly after a rescan takes place.

If it works, please close :)

Ah, and regarding the convention of `address list` I've decided to leave the working as it is now. I think if someone gives a P2TH address a name then it should be for a good reason and he would like to see this address in the standard `address list` output. It's also consistent with the principle of showing all named addresses in the standard view. I'll clarify this a bit in the docstring/manual.

**Comment by buhtignew** [comment]
I've restarted my `slimcoind` with `-rescan` flag and the balance has shown up.
I'm closing this issue.
