### ISSUE TITLE
Transaction list DECK ADDRESS CASUAL_TEXT_HERE -b output

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#57]
By error I've run `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr -b` and got the same output of `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974  mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr -b -a`.
Then I've run `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974  mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr somecasualtexthere -b` and got the same output.

Why is it?
Can we add some message or put some limit in the code to avoid it?

**Comment by d5000** [comment]
The command will ignore all positional arguments after the two leading ones. I will not change this.

**Comment by buhtignew** [comment]
Oh, my 
It's not the first time I'm facing this "issue" and each time it seems to me like I've discovered something really new, I apologize.
I don't know how relevant it could be for the user, but as tester it seems like I've faced it already sometimes.
Is the conversion for the inputted wrong command into the right one occurs implicitly?
Or it would be possible to output a message like "Wrong number of arguments, assuming ACTUALLY_EXECUTED_COMMAND"?

**Comment by d5000** [comment]
I try to explain this a bit more exhaustive way so you understand when and when not you should report issues with "additional" (i.e. not intended) positional arguments.

Pacli (in reality, Fire) processes the list of positional arguments by the order they are included by the user. Until the user enters the first flag (any letter or word preceded by a dash `-`) the commands are processed as if they were positional arguments.

Example: let's say `pacli some_command` has the positional argument DECK and then only 2 keyword arguments `-a ADDRESS` (a string, for a SLM address) and `-d` as a boolean argument (True of False) for "debug", i.e. one that is normally used without the user entering explicitly "True" or "False" - if `-d` is given then it's interpreted as True, and if not, it's False.

The intended usage is thus:

`pacli some_command  my_deck -a my_address [-d]`

Now you can enter also:

`pacli some_command  my_deck my_address [-d]`

In this case my_address is assigned as the value for the `-a` argument. In the code it is designed as a keyword argument, but the user has entered it in a positional way. This can be an "intended" usage, as it allows to add optional positional arguments (we've already discussed this in another issue).

But now let's see the following case: The user enters:

`pacli some_command  my_deck my_address some_other_string`

The some_other_string is now assigned to the `-d` (debug) argument. This makes no sense, as the debug argument only should take the boolean values True or False and normally as written above these values are not entered.

But Fire itself does not check the type of the value. That must be done in the main code. What I am doing normally is the following: I check if the value makes sense for the argument - i.e. if it's a boolean argument like `debug` then I ignore all values which are neither True nor False.

If I wanted to check all the possible arguments an user could erroneously enter, then I would have to add additional branches to the code of all (!) commands which would essentially do nothing in 99,999% of the cases and only would add complexity.

If there was a way to simply get the list of positional arguments (so I could output an error message like the one you suggested if the number of positional arguments is exceeded) it would be perhaps possible but Fire doesn't provide a method for that I'm aware of. What can be done is to check if there are more than the total number of arguments including keyword arguments. But in most cases this would be such a high number of arguments to trigger that message that nobody would ever do that accidentally and it's not worth the hassle.

That's why in most of such cases I'm not willing to "fix the issue" as I'm thinking that this means "guiding" the user too much - there's a docstring and a manual to read - and usually will close the issue.

There is one exception, and this is one you can and should report as an issue (but only if you stumble accidentally upon it): If the command behaves **differently** if you add an additional positional argument than without that argument, i.e. when the code is not properly ignoring the argument. I have checked the code for this recently but there could still be an oversight somewhere.

**Comment by buhtignew** [comment]
I've got your point. I think this issue can be closed.
