### ISSUE TITLE
Transaction list with -z flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#59]
I've been testing `transaction list -z` command and have discovered that the output of `transaction list -z -t` is 1924 in my case while the output of `transaction list -w -t` is 1123. 

Why is it? Are there more raw transactions than those in my wallet?

I've also understood that the `-z` flag doesn't consider the ADDRESS or the DECK string before it, thus the output is always the same with any address. Is it intended?

**Comment by d5000** [comment]
The variant allows basically to test if the wallet is corrupted or there are other problems not related to pacli. It outputs the raw output of `listtransactions` RPC Slimcoin command, and this can bring duplicates. The idea is to stay as close as possible to this command, because the RPC command line interface of `listtransactions` seems to be broken.

There will be no filtering of any kind for this reason. There is no use case other than debugging, and in any case one can filter with grep or other shell utilities. I even am thinking of removing it completely once launch is close.
