### ISSUE TITLE
Rewards transactions

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#61]
If I run `transaction list mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP -t` command I'm getting the total of 183 transactions.
However I'm sure I haven't done manually such a big number of transactions.
I've probably burned some coin from that address so the total of transactions is that high because I'm receiving rewards, but is there any way to see the rewards transaction I've got so far and possibly to separate them from the ordinary receive/sent transactions? (I.e. to see the "manually" received and sent transaction in a separate list.)

**Comment by d5000** [comment]
After the commit which fixes issue #60 you shouldn't see the rewards (coinbase transactions) anymore in the standard view (if you don't use `-v`), and can also count them with `-t`.

If you want to see the list of coinbase (reward) transactions, an idea is:
`pacli transaction list ADDRESS -v -p type`
Those with values `generate` or `immature` are rewards.

**Comment by buhtignew** [comment]
Would it make sense output the coinbase transactions separately with `-v` flag?

**Comment by d5000** [comment]
> Would it make sense to output the coinbase transactions separately with the -v flag?

No. That's outside the scope of a tool to manage/transfer tokens and has no priority. `-v` is already borderline, but it is useful to ignore these transactions for those who are mining because there can be many. Those few users needing to see "only" coinbase transactions can use `-p` and tools like grep or awk to process the results.

Again, I'm not willing to extend pacli to a "swiss army knife" for SLM.

> transaction list  mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -v -p generate

You entered the value for the parameter, not the key. You have to do

> transaction list  mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -v -p type

and then you'll get the correct result.

**Comment by buhtignew** [comment]
My output of `transaction list mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -v -p type` is the following:
```
        General error raised by PeerAssets.

        Check if your input is correct.

        If you gave a deck as an argument, a possible reason for this error is that you need to initialize the deck.

        To initialize the default decks, use:

        pacli deck init

        To initialize a single deck, use:

        pacli deck init DECKID
```
It's probably a bug because the `transaction list mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -v -p value_received` output for instance is correct.

However I think I've got your point, if the `-p type` filter were working correctly the command to filter the coinbase transactions would be `transaction list mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -v -p type | grep -E "generate|immature"`
If so please consider that there is no "generate" or "immature" transaction in my `transaction list mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -v` output.
I feel this discussion may be not that important and we could even drop it, the only my concern is that unconsistency of outputted results with the expectation may hide a bug one is not aware of.

**Comment by d5000** [comment]
Strange, can't reproduce the error you got, not even with your wallet file.

Can you please try it with `-d` option and post the traceback? (This is generally a good idea when you get errors which are "beautified" by pacli, at least for all commands which have the `-d`/`--debug` option).

About the "generate/immature" problem: I just realized my post about the possible grep filtering was wrong, sorry. These categories exist in the `listtransactions` output, but to simplify I changed them all to "receive". I have changed that now because I think it is more useful to get the original categories.

Commit: e4eef69

**Comment by buhtignew** [comment]
> Strange, can't reproduce the error you got, not even with your wallet file.

The error is gone, maybe thanks to the last update.

> About the "generate/immature" problem of the "type" output: I just realized my post about the possible grep filtering was wrong, sorry. These categories exist in the listtransactions output, but to simplify I had changed them all to "receive". I have changed that behaviour now because I think it is more useful to get the original categories, which include 'generate' and 'immature'.

I can see both "generate" as "immature" type of transactions if I run `transaction list -w -v -p type`, but I'm not able to create meaningful list of those transactions if I run `transaction list -w -v -p type | grep -E "immature|generate"`. My output looks like this:
```
       'generate'
        'generate'
        'generate'
        'generate'
```
probably because the transaction id is not on the same line of the "type".
_
Don't know whether it's related, but something similar happens with `transaction list -w -v` output because in the beginning I receive the following list:
```
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
['send'] ['receive']
``` 
and after a while I'm seeing the expected output for some transactions.

**Comment by d5000** [comment]
The send/receive output is actually a print statement I used for debugging this issue and forgot to remove. I apologize.

I haven't pushed the newest changes to the repo (which also removes this print statement) because I'm currently working on the last part of the block locator feature (the integrity test) and it's still largely in an untested state. Basically the problem is that I still need to "cache" a big part of the blockchain to be able to really test it well.

About the filtering of the result: Yes, you're correct, the transaction type is not at the same line than the txid, so you would have to do some shell trickery to get this right. The problem here is the "pretty printing" algorithm which cuts the line after a certain number of characters. I'm unsure if this is worth a change, as so many times there's a conflict between the usability needs of different user groups. Maybe I'll change the `-q` behavior so 1 result per line is outputted. What you can do already is to count the transactions with the "generate" keyword with grep combined with `wc -l`.

**Comment by buhtignew** [comment]
> What you can do already is to count the transactions with the "generate" keyword with grep combined with wc -l.

I can count them already by subtracting `transaction list -w -t` and `transaction list -w -v -t` outputs.

>  I'm unsure if this is worth a change, as so many times there's a conflict between the usability needs of different user groups. 

We can drop this question for the moment, in order to concentrate on the more urgent tests. But I feel we'll basically need a flag to list the coinbase transactions alone at some point. However I can be wrong and we can implement it later if needed.
