### ISSUE TITLE
transaction list -x with receiver's and origin address

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#68]
I've picked out by chance a transaction from my `transaction list -x -f 396100 -e 396205` output, `67ce28ac7ddf6706871f3a0da3cf0e2a46ba492ebf8c26ccd1b09cfe6ab6c5b7`, which seems to have the same receiver and sender there:
```
{
    'txid': '67ce28ac7ddf6706871f3a0da3cf0e2a46ba492ebf8c26ccd1b09cfe6ab6c5b7',
    'inputs': [
        {'sender': ['mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w'], 'value': 5.15}
    ],
    'outputs': [
        {'receivers': [], 'value': 0.0},
        {
            'receivers': ['mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w'],
            'value': 6.052414
        }
    ],
    'blockheight': 396205
}
```
So I've compared the `transaction list -x mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w -o mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w -f 396100 -e 396205 -t` and the `transaction list -x mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w -f 396100 -e 396205 -t` outputs. Both reported 28 transactions.

Then I've compared the outputs without the `-t` flag and found that they are identical.

After that I've picked out the last transaction of the both lists:
```
{
    'txid': '9d93068617e6fa6eabb9163d50c463496ded30c6c743e5ab9132c1a0d37d05fa',
    'type': ['receive'],
    'value_received': 8000.0,
    'confirmations': 374238
}
```
And examined its `transaction show 9d93068617e6fa6eabb9163d50c463496ded30c6c743e5ab9132c1a0d37d05fa -s` output, which doesn't reported the address `mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w` nor as receiver neither as sender:

```
{
    'inputs': [
        {'sender': ['mxuqE6UWREDuWuMkBWoz1F8jfZur5CM3ZH'], 'value': 4500.0},
        {'sender': ['mxuqE6UWREDuWuMkBWoz1F8jfZur5CM3ZH'], 'value': 4500.0}
    ],
    'outputs': [
        {'receivers': ['mpF9FcfSps5jPSG2vDdGVF883xNFez1UGT'], 'value': 0.01},
        {'receivers': [], 'value': 0.01},
        {'receivers': ['mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP'], 'value': 8000.0},
        {'receivers': ['mxuqE6UWREDuWuMkBWoz1F8jfZur5CM3ZH'], 'value': 999.97}
    ],
    'blockheight': 21987
}
```

**Comment by d5000** [comment]
There was an error in the help, sorry. The receiver address comes before the `-x`. I don't know why I didn't see this because all the other modes were already corrected.

So you should have got in the first case all transactions which were sent by mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w in that timeframe, and in the second case, all transactions between both blocsk, if the command worked properly.

But I copied your command as you entered it, and got 93 transactions, which would have been impossible if the command worked correctly. So I realized there is also a (not very severe) bug here: the command didn't ignore properly the (incorrectly entered) value after `-x`, so it went into another branch of the code and instead showed what would have been the result of the command "without" the `-x` flag. This is one of the cases which has to be corrected imo even if it's a case "the user didn't enter the command correctly", so your bug report wasn't in vain :)

The output of the correct command `transaction list mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w  -x -o mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w -f 396100 -e 396205 -t` is 2. I've checked the transactions (538673e9cdb05f804cfabaaa0d1af83c569834050b9ab5bd62f0cf90ee7557ed and 67ce28ac7ddf6706871f3a0da3cf0e2a46ba492ebf8c26ccd1b09cfe6ab6c5b7) and they are really coinstake transactions with the address mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w as sender and receiver. So if the help wasn't incorrect, you would probably have got the correct output. Perhaps you can confirm.

I have still to look which is the best way to fix this problem properly because the if- else branch structure of the command is quite complicated. I'll report it then here once fixed.

**Comment by d5000** [comment]
Update: Unfortunately I had to give up on the plan to "properly ignore" incorrect user entries. There is no way (really) to make this work really consistent with Fire and at the same time allowing optional positional arguments.

This affects only boolean flags, i.e. those which are correctly called only with `--flag` of `-f` (as a short form) and no value.

Thus if the user enters a value (e.g. `--flag=some_value` of `-f some_value`) the flag will be ignored completely. It's like the command had been entered without the flag at all. The only exceptions is if the value happens to be _True_ or _False_.

It is not ideal, I know, but there is no other way. I'll highlight this in the manual. The problem is that if I do this differently, then a previous positional argument, if entered wrongly, can influence the value of a flag immediately after it (in the code), which is worse.

**Comment by buhtignew** [comment]
I've got the point. This is solved.
