### ISSUE TITLE
config default

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#73]
I've tested `config default` command and have discovered that the default setup we have doesn't let using pacli normally.
In fact after I've applied it my pacli.conf file has become as following:
```
[settings]
network = tppc
production = True
deck_version = 1
change = default
provider = rpcnode
rpcuser = sdfjkl
rpcpassword = uiofdkfdsfsdf
rpcport = 9904
compatibility_mode = False
```
Another thing I've experienced is that one doesn't know in advance which parameters will be set up to default.
So for instance I have made a backup copy both of pacli.conf and extended settings I had in order to be able to revert the values after the test if needed.

I know very few people will use this command, but if some unlucky wona-be-a-pro (like me :-) ) tries it he may not be able to understand what he has to do to revert his "default" settings to something that works.

So maybe we can add some hint in the help that the command changes the basic and not the extending settings, and where one should go to revert those values manually (pacli.conf).
And maybe we should backup the pacli.conf that is being overwritten by this command in order for the user to be able to revert his setting back if needed.
Another idea can be to show the changes that will be applied in a dialog that would follow the command input so the user can accept or not the change.
Would be also great to be able for the user to revert the change back if anything goes wrong, but for the moment I think it's impossible because pacli stops working if the default settings are wrong.

**Comment by d5000** [comment]
That's one of the original commands. I see it would make sense to apply the compatibility mode here, and if the compatibility mode is not set a message would be shown, and the user would have to confirm to continue (like in `config set` with compatibility mode enabled).

A "revert function" could be implemented as part of a separate Python script dealing with the config file (e.g. a pacli-cfg script with the commands `pacli-cfg backup` and `pacli-cfg revert`). This would be very easy as it would be a simple file operation and not take much time to develop, and would be the way I'd prefer as a workaround.

Will do this in the coming days (probably not today).

**Comment by d5000** [comment]
Changed the command with commit 5f9615f. If compatibility mode is not set (or `--quiet` option used) then a warning will be displayed and the user will have to confirm to continue. The warning also specifies that in the case the default config is used, the RPC credentials will have to be entered again into pacli.conf (this is the issue which makes pacli unusable).

I believe this is enough to prevent accidental use of this command (which is not very useful by the way, because there are not really many basic settings, and so return to default should never be necessary).

Can be closed if there are no further questions.

**Comment by buhtignew** [comment]
I agree and am closing now.
