### ISSUE TITLE
Slimcoind stuck

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#8]
I've just discovered my `slimcoind` is on the block `244222` that is 84 days old.
My recent server's block is `340863` right now, but when I try to sync my local wallet from scratch there are only `244222` blocks available to download.
When I just connect my local wallet directly to my server using the slimcoin.conf configuration I'm seeing that my local wallet is about to download only `170432` blocks.
I'll try to download a snapshot from my server to overcome the issue, but it will require some time.
Probably I'll not be able to reply the other issues today.

Update: I was able to download the snapshot and make it work on my local wallet. Tomorrow I'll go on with our work. Can you check whether your server is not stuck on 244222 block by chance?

**Comment by d5000** [comment]
Thank you! My server was indeed stuck on this block (244222) too. I thought actually your server was not mining. I've restarted it and am redownloading the blockchain. Probably it got stuck on an orphan block and then banned your server because my client also was on this block. I'll close as I think this should be easy to solve.
