### ISSUE TITLE
transaction list -x with different flags

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#80]
I've tested `transaction list -x -f 156492 -e 156902 -t` with different flags.

The total number of transaction in that interval is 22.
Only the `-b` flag shows a different number of transactions, 11.
All the other tested flags, i.e. `-s`, `-r`, `-g`,  `-c`, `-u`  have reported 22 transactions. Thus I assume these flags are ignored.
Don't they?

**Comment by d5000** [comment]
-u (unclaimed) option is not supported for this mode. Added the incompatibility to the help.

-g should normally work, as does -b, but probably you didn't add a deck as first positional argument. This mode was not explained in the help, so I added it. Its syntax is:

`pacli transaction list DECK -g [-o ORIGIN_ADDRESS] [-f STARTHEIGHT] [-e ENDHEIGHT]`

For -s and -r I'll look into it if it's a bug because these should normally work with -x.

**Comment by d5000** [comment]
I looked again into this issue and what I wrote before was wrong. `--send` and `--received` are not supported in `-x` mode. The reason is simply that they make no sense, because you don't have your wallet as a "reference".

To try to explain that in simpler words: If you see a transaction from the perspective of your wallet, there are transactions which are "sent" and "received" - sent are those where an address from your wallet is one of the sender, and received if one of those is one of the receivers. However for the `-x` mode all addresses are equal because it looks directly at the blockchain, not at your particular wallet like the other modes.

Instead the `-o` option gives you the opportunity to filter the transactions by a sending address, and the address you can enter as positional argument directly after `transaction list` is the receiving address (this is not supported by the `-g` and `-b` modes because these use the "receiving address" defined by an AT or PoB deck, in the case of PoB the burn address).

I think this can be closed thus.

**Comment by buhtignew** [comment]
I was suspecting something like this.
I'm closing this issue now.
